import { optionState } from "./app-logic.js";

const $ = (id) => document.getElementById(id);
const titles = { "pdf-single": "阿里云大模型ACP认证题库（单选题）", "pdf-multi": "阿里云大模型ACP认证题库（多选题）" };
let sets = [], progress = {}, setIndex = 0, qIndex = 0, question = null, selected = [], submitted = false, pendingQuestion = null, mode = "all", filters = { wrong: false, favorite: false, excludeChopped: true };
const request = (url, options) => fetch(url, options).then((response) => { if (!response.ok) throw new Error("请求失败"); return response.status === 204 ? null : response.json(); });
const emptyState = () => ({ done: [], wrong: [], favorite: [], excluded: [], results: {}, answers: {} });
const state = (index = setIndex) => (progress[String(index)] ??= emptyState());
const allQuestions = (index = setIndex) => Array.from({ length: sets[index].question_count }, (_, number) => number);
const active = (index = setIndex) => allQuestions(index).filter((number) => !state(index).excluded.includes(number));
const questionsForMode = () => { const current = state(); if (mode === "chopped") return allQuestions().filter((number) => current.excluded.includes(number)); return allQuestions().filter((number) => (!filters.excludeChopped || !current.excluded.includes(number)) && (!filters.wrong || current.wrong.includes(number)) && (!filters.favorite || current.favorite.includes(number))); };
const save = () => request("/api/progress", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ progress }) });
function updateModeButtons() { $("wrongBtn").classList.toggle("on", filters.wrong); $("favoriteBtn").classList.toggle("on", filters.favorite); $("choppedBtn").classList.toggle("on", mode === "chopped"); }
function renderSets() { $("sets").innerHTML = sets.map((set, index) => `<button class="set-btn ${index === setIndex ? "active" : ""}" data-set="${index}">${titles[set.source_key]}<small>${set.question_count - state(index).excluded.length}</small></button>`).join(""); document.querySelectorAll("[data-set]").forEach((button) => button.onclick = () => { setIndex = Number(button.dataset.set); mode = "all"; qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; updateModeButtons(); loadQuestion(); }); }
function renderCounts() { const totals = sets.reduce((counts, _, index) => { const current = state(index); counts.wrong += current.wrong.filter((number) => !current.excluded.includes(number)).length; counts.favorite += current.favorite.length; counts.chopped += current.excluded.length; return counts; }, { wrong: 0, favorite: 0, chopped: 0 }); $("wrongCount").textContent = totals.wrong; $("favoriteCount").textContent = totals.favorite; $("choppedCount").textContent = totals.chopped; }
function renderActivity() { const current = state(), isPending = !current.done.includes(qIndex) && !current.excluded.includes(qIndex); if (isPending) pendingQuestion = { setIndex, qIndex }; sets.forEach((set, index) => { const multi = set.section === "multi", panel = $(multi ? "activityPanelMulti" : "activityPanelSingle"), grid = $(multi ? "activityGridMulti" : "activityGridSingle"), summary = $(multi ? "activitySummaryMulti" : "activitySummarySingle"), setProgress = state(index), done = setProgress.done.length, correct = setProgress.done.filter((number) => setProgress.results[String(number)]).length, numbers = allQuestions(index).filter((number) => (!filters.excludeChopped || !setProgress.excluded.includes(number)) && (!filters.wrong || setProgress.wrong.includes(number)) && (!filters.favorite || setProgress.favorite.includes(number))); summary.textContent = `${done} / ${set.question_count} 题已完成`; panel.hidden = index !== setIndex; panel.querySelector("[data-set-score]").textContent = `${done ? Math.round((correct / done) * 100) : 0}%`; grid.style.gridTemplateColumns = `repeat(${Math.ceil(numbers.length / 7)}, 10px)`; grid.innerHTML = numbers.map((number) => { const chopped = setProgress.excluded.includes(number), completed = setProgress.done.includes(number), pending = pendingQuestion?.setIndex === index && pendingQuestion?.qIndex === number, viewing = index === setIndex && number === qIndex && (completed || chopped), status = chopped ? "done chopped" : setProgress.wrong.includes(number) ? "wrong" : setProgress.favorite.includes(number) ? "favorite" : completed ? "done" : ""; return `<button class="activity-cell ${status}${pending ? " current" : ""}${viewing ? " viewing" : ""}" data-question="${index}:${number}">${pending ? "?" : ""}</button>`; }).join(""); grid.querySelectorAll("[data-question]").forEach((button) => button.onclick = () => { [setIndex, qIndex] = button.dataset.question.split(":").map(Number); mode = "all"; updateModeButtons(); loadQuestion(); }); }); renderFilters(); }
function renderQuestion() { if (!question) return; const multi = question.section === "multi", current = state(), favorite = current.favorite.includes(qIndex); $("setTitle").textContent = titles[question.source_key]; $("card").innerHTML = `<div class="q-meta"><span class="tag">${multi ? "多选题" : "单选题"}</span><span>题号 ${question.question_no}</span></div><h3 class="question">${question.body}</h3><div class="options">${question.options.map((option) => `<button class="option ${optionState(option.key, selected, question.correct_answer, submitted)}" data-option="${option.key}"><span class="letter">${option.key}</span><span>${option.text}</span></button>`).join("")}</div>${submitted ? `<div class="answer-note">正确答案：<b>${question.correct_answer.split("").join("、")}</b></div>` : ""}<div class="controls"><div><button class="btn" id="prev">上一题</button> <button class="btn" id="favoriteCurrent">${favorite ? "取消收藏" : "收藏本题"}</button> <button class="btn" id="chop">${mode === "chopped" ? "恢复本题" : "斩题"}</button></div><span class="hint">${multi ? "可选择多个选项" : "请选择一个选项"}</span><button class="btn primary" id="submit">${submitted ? "下一题" : "提交答案"}</button></div>`; document.querySelectorAll("[data-option]").forEach((button) => button.onclick = () => { if (submitted) return; const key = button.dataset.option; selected = multi ? selected.includes(key) ? selected.filter((item) => item !== key) : [...selected, key] : [key]; renderQuestion(); }); $("prev").onclick = () => { const list = questionsForMode(), position = list.indexOf(qIndex); if (position > 0) { qIndex = list[position - 1]; loadQuestion(); } }; $("favoriteCurrent").onclick = async () => { current.favorite = favorite ? current.favorite.filter((number) => number !== qIndex) : [...current.favorite, qIndex]; await save(); renderCounts(); renderActivity(); renderQuestion(); }; $("chop").onclick = chopCurrent; $("submit").onclick = () => submitted ? nextQuestion() : submitAnswer(); }
async function chopCurrent() { const current = state(); if (mode === "chopped") current.excluded = current.excluded.filter((number) => number !== qIndex); else if (!current.excluded.includes(qIndex)) current.excluded.push(qIndex); if (pendingQuestion?.setIndex === setIndex && pendingQuestion.qIndex === qIndex) pendingQuestion = null; await save(); const list = questionsForMode(); qIndex = list[0] ?? active()[0] ?? 0; renderCounts(); loadQuestion(); }
async function submitAnswer() { if (!selected.length) return; const result = await request(`/api/quiz/questions/${question.source_key}/${question.question_no}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer: selected.join("") }) }); Object.assign(question, result); const current = state(); if (!current.done.includes(qIndex)) current.done.push(qIndex); current.results[String(qIndex)] = result.is_correct; current.answers[String(qIndex)] = selected.join(""); current.wrong = result.is_correct ? current.wrong.filter((number) => number !== qIndex) : [...new Set([...current.wrong, qIndex])]; if (pendingQuestion?.setIndex === setIndex && pendingQuestion.qIndex === qIndex) pendingQuestion = null; await save(); submitted = true; renderCounts(); renderActivity(); renderQuestion(); }
function nextQuestion() { const list = questionsForMode(), position = list.indexOf(qIndex); if (position < list.length - 1) { qIndex = list[position + 1]; loadQuestion(); } }
async function loadQuestion() { selected = []; submitted = false; question = await request(`/api/quiz/questions/${sets[setIndex].source_key}/${qIndex + 1}`); renderSets(); renderCounts(); renderActivity(); renderQuestion(); }
function exportProgress() { const blob = new Blob([JSON.stringify(progress, null, 2)], { type: "application/json" }), link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "acp-progress.json"; link.click(); URL.revokeObjectURL(link.href); }
async function start() { const [catalog, saved] = await Promise.all([request("/api/quiz/catalog"), request("/api/progress")]); sets = catalog.sets; progress = saved; setIndex = sets.findIndex((_, index) => state(index).done.length > 0); if (setIndex < 0) setIndex = 0; qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; $("randomBtn").onclick = () => { const list = questionsForMode(); qIndex = list[Math.floor(Math.random() * list.length)] ?? qIndex; loadQuestion(); }; $("wrongBtn").onclick = () => setMode("wrong"); $("favoriteBtn").onclick = () => setMode("favorite"); $("choppedBtn").onclick = () => setMode("chopped"); $("exportBtn").onclick = exportProgress; $("resetBtn").onclick = async () => { const current = state(); current.done = []; current.wrong = []; current.results = {}; current.answers = {}; await save(); qIndex = active()[0] ?? 0; loadQuestion(); }; updateModeButtons(); loadQuestion(); }
function renderFilters() { document.querySelectorAll("[data-filter]").forEach((input) => { input.checked = filters[input.dataset.filter]; input.onchange = () => { filters[input.dataset.filter] = input.checked; mode = "all"; qIndex = questionsForMode()[0] ?? 0; updateModeButtons(); loadQuestion(); }; }); }
function setMode(nextMode) { if (nextMode === "wrong" || nextMode === "favorite") { filters[nextMode] = !filters[nextMode]; mode = "all"; } else mode = mode === nextMode ? "all" : nextMode; qIndex = questionsForMode()[0] ?? 0; updateModeButtons(); loadQuestion(); }
start().catch((error) => { $("card").innerHTML = `<div class="empty">${error.message}</div>`; });
