import { completionStats, isCurrentLoad, nextQuestionIndex, optionState, questionSetCount, shouldKeepSubmittedQuestion } from "./app-logic.js";

const $ = (id) => document.getElementById(id);
const titles = { "pdf-single": "阿里云大模型ACP认证题库（单选题）", "pdf-multi": "阿里云大模型ACP认证题库（多选题）" };
let sets = [], progress = {}, setIndex = 0, qIndex = 0, question = null, selected = [], submitted = false, pendingQuestion = null, mode = "all", filters = { wrong: false, favorite: false, chopped: false, unfinished: false, all: true }, questionLoadId = 0;
const request = (url, options) => fetch(url, options).then((response) => { if (!response.ok) throw new Error("请求失败"); return response.status === 204 ? null : response.json(); });
const emptyState = () => ({ done: [], wrong: [], favorite: [], excluded: [], results: {}, answers: {} });
const state = (index = setIndex) => (progress[String(index)] ??= emptyState());
const allQuestions = (index = setIndex) => Array.from({ length: sets[index].question_count }, (_, number) => number);
const active = (index = setIndex) => allQuestions(index).filter((number) => !state(index).excluded.includes(number));
const filterKinds = () => ["wrong", "favorite", "chopped", "unfinished"].filter((kind) => filters[kind]);
const matchesFilters = (number, current) => { const kinds = filterKinds(); if (filters.all || !kinds.length) return true; return kinds.some((kind) => kind === "wrong" ? current.wrong.includes(number) && !current.excluded.includes(number) : kind === "favorite" ? current.favorite.includes(number) && !current.excluded.includes(number) : kind === "chopped" ? current.excluded.includes(number) : !current.done.includes(number) && !current.excluded.includes(number)); };
const filteredQuestions = (index = setIndex) => allQuestions(index).filter((number) => matchesFilters(number, state(index)) || shouldKeepSubmittedQuestion(number, qIndex, index, setIndex, filters, state(index).done, state(index).excluded));
const questionsForMode = () => { const current = state(); if (mode === "chopped") return allQuestions().filter((number) => current.excluded.includes(number)); return filteredQuestions(); };
const save = () => request("/api/progress", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ progress }) });
function renderSets() { $("sets").innerHTML = sets.map((set, index) => { const count = questionSetCount(set); return '<button class="set-btn ' + (index === setIndex ? "active" : "") + '" data-set="' + index + '">' + titles[set.source_key] + '<small>' + count + '</small></button>'; }).join(""); document.querySelectorAll("[data-set]").forEach((button) => button.onclick = () => { setIndex = Number(button.dataset.set); mode = "all"; qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; loadQuestion(); }); }
function renderActivity() { const current = state(), isPending = !current.done.includes(qIndex) && !current.excluded.includes(qIndex); if (isPending) pendingQuestion = { setIndex, qIndex }; sets.forEach((set, index) => { const multi = set.section === "multi", panel = $(multi ? "activityPanelMulti" : "activityPanelSingle"), grid = $(multi ? "activityGridMulti" : "activityGridSingle"), summary = $(multi ? "activitySummaryMulti" : "activitySummarySingle"), setProgress = state(index), stats = completionStats(setProgress), numbers = filteredQuestions(index); summary.textContent = stats.completed + " / " + questionSetCount(set) + " 题已完成"; panel.hidden = index !== setIndex; panel.querySelector("[data-set-score]").textContent = (stats.completed ? Math.round(stats.correct / stats.completed * 100) : 0) + "%"; grid.style.gridTemplateColumns = "repeat(" + Math.ceil(numbers.length / 7) + ", 10px)"; grid.innerHTML = numbers.map((number) => { const chopped = setProgress.excluded.includes(number), completed = setProgress.done.includes(number), pending = pendingQuestion?.setIndex === index && pendingQuestion?.qIndex === number, viewing = index === setIndex && number === qIndex && (completed || chopped), status = chopped ? "done chopped" : filters.favorite && !filters.wrong && setProgress.favorite.includes(number) ? "favorite" : setProgress.wrong.includes(number) ? "wrong" : setProgress.favorite.includes(number) ? "favorite" : completed ? "done" : ""; return '<button class="activity-cell ' + status + (pending ? " current" : "") + (viewing ? " viewing" : "") + '" data-question="' + index + ':' + number + '">' + (pending ? "?" : "") + "</button>"; }).join(""); grid.querySelectorAll("[data-question]").forEach((button) => button.onclick = () => { [setIndex, qIndex] = button.dataset.question.split(":").map(Number); mode = "all"; loadQuestion(); }); }); renderFilters(); }
function renderQuestion() { if (!question) return; const multi = question.section === "multi", current = state(), favorite = current.favorite.includes(qIndex), list = questionsForMode(), nextIndex = nextQuestionIndex(list, qIndex); $("setTitle").textContent = titles[question.source_key]; $("card").innerHTML = `<div class="q-meta"><span class="tag">${multi ? "多选题" : "单选题"}</span><span>题号 ${question.question_no}</span></div><h3 class="question">${question.body}</h3><div class="options">${question.options.map((option) => `<button class="option ${optionState(option.key, selected, question.correct_answer, submitted, multi)}" data-option="${option.key}"><span class="letter">${option.key}</span><span>${option.text}</span></button>`).join("")}</div>${submitted ? `<div class="answer-note">正确答案：<b>${question.correct_answer.split("").join("、")}</b></div>` : ""}<div class="controls"><div><button class="btn" id="prev">上一题</button> <button class="btn" id="favoriteCurrent">${favorite ? "取消收藏" : "收藏本题"}</button> <button class="btn" id="chop">${mode === "chopped" ? "恢复本题" : "斩题"}</button></div>${multi && selected.length === 1 ? '<span class="hint">当前是多选模块</span>' : ""}<div class="controls-actions"><button class="btn" id="next"${nextIndex === null ? " disabled" : ""}>下一题</button>${submitted ? "" : '<button class="btn primary" id="submit">提交答案</button>'}</div></div>`; document.querySelectorAll("[data-option]").forEach((button) => button.onclick = () => { if (submitted) return; const key = button.dataset.option; selected = multi ? selected.includes(key) ? selected.filter((item) => item !== key) : [...selected, key] : [key]; renderQuestion(); }); $("prev").onclick = () => { const list = questionsForMode(), position = list.indexOf(qIndex); if (position > 0) { qIndex = list[position - 1]; loadQuestion(); } }; $("next").onclick = () => { if (nextIndex !== null) { qIndex = nextIndex; loadQuestion(); } }; $("favoriteCurrent").onclick = async () => { current.favorite = favorite ? current.favorite.filter((number) => number !== qIndex) : [...current.favorite, qIndex]; await save(); renderActivity(); renderQuestion(); }; $("chop").onclick = chopCurrent; $("submit")?.addEventListener("click", submitAnswer); }
async function chopCurrent() { const previousList = questionsForMode(), position = previousList.indexOf(qIndex), current = state(); if (mode === "chopped") current.excluded = current.excluded.filter((number) => number !== qIndex); else if (!current.excluded.includes(qIndex)) current.excluded.push(qIndex); if (pendingQuestion?.setIndex === setIndex && pendingQuestion.qIndex === qIndex) pendingQuestion = null; await save(); const list = questionsForMode(); qIndex = previousList.slice(position + 1).find((number) => list.includes(number)) ?? list[0] ?? active()[0] ?? 0; loadQuestion(); }
async function submitAnswer() { if (!selected.length) return; const result = await request(`/api/quiz/questions/${question.source_key}/${question.question_no}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer: selected.join("") }) }); Object.assign(question, result); const current = state(); if (!current.done.includes(qIndex)) current.done.push(qIndex); current.results[String(qIndex)] = result.is_correct; current.answers[String(qIndex)] = selected.join(""); current.wrong = result.is_correct ? current.wrong.filter((number) => number !== qIndex) : [...new Set([...current.wrong, qIndex])]; if (pendingQuestion?.setIndex === setIndex && pendingQuestion.qIndex === qIndex) pendingQuestion = null; await save(); submitted = true; renderActivity(); renderQuestion(); }
async function loadQuestion() { const loadId = ++questionLoadId, requestedSetIndex = setIndex, requestedQuestionIndex = qIndex, current = state(requestedSetIndex), savedAnswer = current.answers[String(requestedQuestionIndex)] ?? ""; selected = savedAnswer.split(""); submitted = current.done.includes(requestedQuestionIndex) && Boolean(savedAnswer); const loadedQuestion = await request(`/api/quiz/questions/${sets[requestedSetIndex].source_key}/${requestedQuestionIndex + 1}`); if (!isCurrentLoad(loadId, questionLoadId)) return; question = loadedQuestion; if (submitted) { const result = await request(`/api/quiz/questions/${question.source_key}/${question.question_no}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer: savedAnswer }) }); if (!isCurrentLoad(loadId, questionLoadId)) return; Object.assign(question, result); } renderSets(); renderActivity(); renderQuestion(); }
function exportProgress() { window.location.assign("/api/progress/export"); }
async function importProgress(file) { const raw = await file.text(); let backup; try { backup = JSON.parse(raw); } catch { window.alert("导入失败：请选择有效的进度备份文件。"); return; } if (!window.confirm("导入将覆盖当前 MySQL 中的全部练习进度，且无法撤销。是否继续？")) return; try { progress = await request("/api/progress/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(backup) }); setIndex = sets.findIndex((_, index) => state(index).done.length > 0); if (setIndex < 0) setIndex = 0; qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; await loadQuestion(); } catch { window.alert("导入失败：文件格式或题库版本不匹配。"); } }
async function resetProgress(kinds) { const current = state(); if (kinds.includes("all")) { current.done = []; current.wrong = []; current.favorite = []; current.excluded = []; current.results = {}; current.answers = {}; } else { if (kinds.includes("favorite")) current.favorite = []; if (kinds.includes("chopped")) current.excluded = []; if (kinds.includes("wrong")) { const wrong = new Set(current.wrong); current.done = current.done.filter((number) => !wrong.has(number)); current.wrong = []; current.results = Object.fromEntries(Object.entries(current.results).filter(([number]) => !wrong.has(Number(number)))); current.answers = Object.fromEntries(Object.entries(current.answers).filter(([number]) => !wrong.has(Number(number)))); } if (kinds.includes("unfinished")) { const done = new Set(current.done), excluded = new Set(current.excluded); current.answers = Object.fromEntries(Object.entries(current.answers).filter(([number]) => done.has(Number(number)) || excluded.has(Number(number)))); } } await save(); qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; await loadQuestion(); }

function handleKeyboard(event) {
  if (event.defaultPrevented || event.ctrlKey || event.metaKey || event.altKey) return;
  const target = event.target;
  if (target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || target?.isContentEditable) return;
  if (event.key === "Escape") {
    if (!submitted && selected.length) {
      selected = [];
      renderQuestion();
      event.preventDefault();
    } else if (document.activeElement instanceof HTMLElement && document.activeElement !== document.body) {
      document.activeElement.blur();
    }
    return;
  }
  if (!question) return;
  if (/^[1-4]$/.test(event.key) && !submitted) {
    const option = question.options[Number(event.key) - 1];
    if (!option) return;
    const multi = question.section === "multi";
    selected = multi
      ? selected.includes(option.key)
        ? selected.filter((key) => key !== option.key)
        : [...selected, option.key]
      : [option.key];
    renderQuestion();
    event.preventDefault();
    return;
  }
  const action = event.key === "Enter" && !submitted
    ? $("submit")
    : event.key === "ArrowLeft"
      ? $("prev")
      : event.key === "ArrowRight"
        ? $("next")
        : event.key.toLowerCase() === "f"
          ? $("favoriteCurrent")
          : event.key.toLowerCase() === "x"
            ? $("chop")
            : null;
  if (!action || action.disabled) return;
  action.click();
  event.preventDefault();
}

async function start() { const [catalog, saved] = await Promise.all([request("/api/quiz/catalog"), request("/api/progress")]); sets = catalog.sets; progress = saved; setIndex = sets.findIndex((_, index) => state(index).done.length > 0); if (setIndex < 0) setIndex = 0; qIndex = active().find((number) => !state().done.includes(number)) ?? active()[0] ?? 0; $("randomBtn").onclick = () => { const list = questionsForMode(); qIndex = list[Math.floor(Math.random() * list.length)] ?? qIndex; loadQuestion(); }; $("exportBtn").onclick = exportProgress; $("importBtn").onclick = () => $("importFile").click(); $("importFile").onchange = async () => { const [file] = $("importFile").files; $("importFile").value = ""; if (file) await importProgress(file); }; loadQuestion(); }
function renderFilters() { document.querySelectorAll("[data-filter]").forEach((input) => { input.checked = filters[input.dataset.filter]; input.onchange = () => { const kind = input.dataset.filter; if (kind === "all") { filters = { wrong: false, favorite: false, chopped: false, unfinished: false, all: input.checked }; } else { filters[kind] = input.checked; if (input.checked) filters.all = false; if (!filterKinds().length) filters.all = true; } mode = "all"; const list = questionsForMode(), current = state(); qIndex = list.find((number) => !current.done.includes(number) && !current.excluded.includes(number)) ?? list[0] ?? 0; loadQuestion(); }; }); document.querySelectorAll("[data-reset-selected]").forEach((button) => button.onclick = async () => { const kinds = filters.all || !filterKinds().length ? ["all"] : filterKinds(); const labels = { wrong: "错题", favorite: "收藏", chopped: "已斩题", unfinished: "未做题", all: "全部" }; const scope = kinds.map((kind) => labels[kind]).join("、"); if (window.confirm("将重置当前套卷的" + scope + "，此操作不可撤销。是否继续？")) await resetProgress(kinds); }); }
window.addEventListener("keydown", handleKeyboard);
start().catch((error) => { $("card").innerHTML = `<div class="empty">${error.message}</div>`; });
